import Head from 'next/head'
import Image from 'next/image'
import Main from './components/Main'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Login from './components/Login'
import Products from './components/Products'

export default function Home() {
  const [login, setLogin] = useState(false)
  const [user, setUser] = useState(null)

  if(!login) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Marketplace</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Login setLogin={setLogin} setUser={setUser}/>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by Kings
          </a>
        </footer>
      </div>
    )
  } 
  else {
    return (
      <div className={styles.container}>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Main user={user}/>
        <Products />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Kings
        </a>
      </footer>
    </div>
      )
  }


}
